/**
 * ChartDisplay — renders Code Interpreter image artifacts.
 *
 * Accepts a resolved ChartArtifact whose `src` is either a data URL
 * (base64-inlined PNG/JPEG) or a remote URL.
 */

import type { ChartArtifact } from "../types";

export interface ChartDisplayProps {
  chart: ChartArtifact | null;
}

export function ChartDisplay({ chart }: ChartDisplayProps) {
  if (!chart) {
    return (
      <div className="chart chart--empty" aria-hidden="true">
        No chart yet.
      </div>
    );
  }
  return (
    <figure className="chart">
      <img
        className="chart__img"
        src={chart.src}
        alt="Code Interpreter chart"
      />
      <figcaption className="chart__caption">
        Generated by Foundry Code Interpreter ({chart.mimeType})
      </figcaption>
    </figure>
  );
}
