apiVersion: v1
kind: Service
metadata:
  name: ops-agent-svc
  namespace: default
  labels:
    app: ops-agent
spec:
  type: ClusterIP
  selector:
    app: ops-agent
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
